-- ============================================
-- FTM Garments Warehouse Tracking System
-- Complete Database Schema
-- Generated: 2026-09-24 from live DB (20 migrations applied)
-- ============================================
-- DO NOT edit this file manually.
-- It is regenerated from the live database whenever migrations are applied.
-- To set up a new server: create the database, then run:
--   php backend/database/migrate.php
-- ============================================

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

CREATE DATABASE IF NOT EXISTS `warehouse_tracking`
  DEFAULT CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;
USE `warehouse_tracking`;

-- ============================================
-- app_settings
-- ============================================
CREATE TABLE IF NOT EXISTS `app_settings` (
  `key` varchar(64) NOT NULL,
  `value` varchar(255) NOT NULL DEFAULT '',
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ============================================
-- shipments
-- ============================================
CREATE TABLE IF NOT EXISTS `shipments` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `internal_po_number` varchar(100) NOT NULL COMMENT 'Internal PO number (unique identifier)',
  `customer` varchar(50) DEFAULT 'MRP' COMMENT 'Customer name (MRP, OTB, OBSW, etc.)',
  `customer_order_no` varchar(50) DEFAULT NULL COMMENT 'MRP/customer order number from .mrpg PoNumber',
  `file_name` varchar(255) NOT NULL COMMENT 'Original XML filename or manual entry identifier',
  `import_date` datetime NOT NULL DEFAULT current_timestamp() COMMENT 'Date when shipment was imported/created',
  `style` varchar(100) DEFAULT NULL COMMENT 'Product style',
  `color` varchar(50) DEFAULT NULL COMMENT 'Product color',
  `order_qty` int(11) DEFAULT NULL COMMENT 'Total order quantity',
  `entry_type` enum('xml','manual') DEFAULT 'xml' COMMENT 'How the shipment was created',
  `schedule_status` enum('linked','unlinked','manual') NOT NULL DEFAULT 'manual' COMMENT 'Schedule link state',
  `schedule_id` int(11) DEFAULT NULL COMMENT 'Matched delivery_schedules.id',
  `schedule_week_label` varchar(50) DEFAULT NULL COMMENT 'Week label from matched schedule',
  `warehouse_order_status` varchar(50) NOT NULL DEFAULT 'active' COMMENT 'Spec 1.5: active, shipped, cancelled, not_audited, failed_audit, waiting_for_booking',
  `quantity` int(11) DEFAULT NULL COMMENT 'Legacy quantity field',
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `updated_at` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `internal_po_number` (`internal_po_number`),
  KEY `idx_customer` (`customer`),
  KEY `idx_import_date` (`import_date`),
  KEY `idx_entry_type` (`entry_type`),
  KEY `idx_shipments_customer_order_no` (`customer_order_no`),
  KEY `idx_shipments_schedule_status` (`schedule_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================
-- cartons
-- ============================================
CREATE TABLE IF NOT EXISTS `cartons` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `shipment_id` int(11) NOT NULL COMMENT 'Foreign key to shipments table',
  `po_number` varchar(50) DEFAULT NULL COMMENT 'Customer order number',
  `pre_pack_id` varchar(50) DEFAULT NULL COMMENT 'PrePackId from XML',
  `barcode_2d` varchar(100) NOT NULL COMMENT 'Unique carton barcode for scanning',
  `size` varchar(20) DEFAULT NULL COMMENT 'Size information',
  `units` int(11) DEFAULT NULL COMMENT 'Number of units in carton',
  `item` varchar(100) DEFAULT NULL COMMENT 'Item information',
  `transfer_number` varchar(50) DEFAULT NULL COMMENT 'Transfer number from XML',
  `transfer_number_end_four` varchar(20) DEFAULT NULL COMMENT 'Last four characters of transfer number',
  `sequence_number` varchar(50) DEFAULT NULL COMMENT 'Sequence number from XML',
  `heading` varchar(50) DEFAULT NULL COMMENT 'Heading from XML',
  `division` varchar(50) DEFAULT NULL COMMENT 'Division information from XML',
  `reserve_or_xdock` varchar(20) DEFAULT NULL COMMENT 'Reserve or Xdock status from XML',
  `total_sequence_number` varchar(20) DEFAULT NULL COMMENT 'Total sequence number from XML',
  `wave_category` varchar(50) DEFAULT NULL COMMENT 'Wave category from XML',
  `print_date` varchar(20) DEFAULT NULL COMMENT 'Print date from XML',
  `depot_store_code` varchar(20) DEFAULT NULL COMMENT 'Depot store code from XML',
  `qc_number` varchar(50) DEFAULT NULL COMMENT 'Manually entered QC number',
  `finishing_number` varchar(50) DEFAULT NULL COMMENT 'Manually entered finishing number',
  `status` enum('pending','entered','exited') NOT NULL DEFAULT 'pending' COMMENT 'Current status of carton',
  `scan_timestamp` datetime DEFAULT NULL COMMENT 'Timestamp when carton was scanned/entered',
  `entry_timestamp` datetime DEFAULT NULL COMMENT 'When carton entered warehouse',
  `exit_timestamp` datetime DEFAULT NULL COMMENT 'When carton exited warehouse',
  `scanned_by` varchar(100) DEFAULT NULL COMMENT 'User who scanned the carton',
  `scan_type` enum('entry','exit') DEFAULT NULL COMMENT 'Type of scan (entry/exit)',
  `truck_shipment_id` int(11) DEFAULT NULL COMMENT 'Link to truck shipment for exit scans',
  `notes` text DEFAULT NULL COMMENT 'Additional notes or comments',
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `updated_at` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `barcode_2d` (`barcode_2d`),
  KEY `shipment_id` (`shipment_id`),
  KEY `idx_status` (`status`),
  KEY `idx_scan_timestamp` (`scan_timestamp`),
  KEY `idx_po_number` (`po_number`),
  KEY `idx_truck_shipment_id` (`truck_shipment_id`),
  KEY `idx_shipment_status` (`shipment_id`,`status`),
  KEY `idx_entry_timestamp` (`entry_timestamp`),
  KEY `idx_exit_timestamp` (`exit_timestamp`),
  CONSTRAINT `cartons_ibfk_1` FOREIGN KEY (`shipment_id`) REFERENCES `shipments` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================
-- users
-- ============================================
CREATE TABLE IF NOT EXISTS `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(50) NOT NULL COMMENT 'Unique username',
  `password` varchar(255) NOT NULL COMMENT 'Hashed password (bcrypt)',
  `role` enum('admin','user','viewer') NOT NULL DEFAULT 'user' COMMENT 'User role',
  `full_name` varchar(100) DEFAULT NULL COMMENT 'Full name of user',
  `email` varchar(100) DEFAULT NULL COMMENT 'Email address',
  `is_active` tinyint(1) NOT NULL DEFAULT 1 COMMENT 'Account active status',
  `last_login` datetime DEFAULT NULL COMMENT 'Last login timestamp',
  `failed_login_attempts` int(11) NOT NULL DEFAULT 0 COMMENT 'Number of failed login attempts',
  `locked_until` datetime DEFAULT NULL COMMENT 'Account locked until this time',
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `updated_at` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `username` (`username`),
  KEY `idx_username` (`username`),
  KEY `idx_is_active` (`is_active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================
-- employees
-- ============================================
CREATE TABLE IF NOT EXISTS `employees` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `employee_code` varchar(20) NOT NULL COMMENT 'Unique employee code for login',
  `employee_name` varchar(100) NOT NULL COMMENT 'Full name of employee',
  `role` enum('scanner','supervisor','admin') NOT NULL DEFAULT 'scanner' COMMENT 'Employee role',
  `is_active` tinyint(1) NOT NULL DEFAULT 1 COMMENT 'Account active status',
  `last_login` datetime DEFAULT NULL COMMENT 'Last login timestamp',
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `updated_at` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `employee_code` (`employee_code`),
  KEY `idx_employee_code` (`employee_code`),
  KEY `idx_is_active` (`is_active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================
-- employee_sessions
-- ============================================
CREATE TABLE IF NOT EXISTS `employee_sessions` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `employee_id` int(11) NOT NULL COMMENT 'Foreign key to employees',
  `token` varchar(64) NOT NULL COMMENT 'Session token',
  `expires_at` datetime NOT NULL COMMENT 'Session expiration time',
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `token` (`token`),
  KEY `employee_id` (`employee_id`),
  KEY `idx_expires_at` (`expires_at`),
  CONSTRAINT `employee_sessions_ibfk_1` FOREIGN KEY (`employee_id`) REFERENCES `employees` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================
-- scan_audit_log
-- ============================================
CREATE TABLE IF NOT EXISTS `scan_audit_log` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `carton_id` int(11) NOT NULL COMMENT 'Foreign key to cartons',
  `scan_type` enum('entry','exit') NOT NULL COMMENT 'Type of scan',
  `scan_timestamp` datetime NOT NULL DEFAULT current_timestamp() COMMENT 'When the scan occurred',
  `scanned_by` varchar(100) DEFAULT NULL COMMENT 'User who performed the scan',
  `truck_shipment_id` int(11) DEFAULT NULL COMMENT 'Truck shipment for exit scans',
  `previous_status` enum('pending','entered','exited') DEFAULT NULL COMMENT 'Status before scan',
  `new_status` enum('pending','entered','exited') NOT NULL COMMENT 'Status after scan',
  `notes` text DEFAULT NULL COMMENT 'Additional notes',
  PRIMARY KEY (`id`),
  KEY `carton_id` (`carton_id`),
  KEY `idx_scan_timestamp` (`scan_timestamp`),
  KEY `idx_scan_type` (`scan_type`),
  CONSTRAINT `scan_audit_log_ibfk_1` FOREIGN KEY (`carton_id`) REFERENCES `cartons` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================
-- scan_sessions
-- ============================================
CREATE TABLE IF NOT EXISTS `scan_sessions` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `session_date` date NOT NULL,
  `po_number` varchar(100) NOT NULL,
  `operator_name` varchar(100) DEFAULT NULL,
  `started_at` datetime NOT NULL,
  `last_activity_at` datetime NOT NULL,
  `total_scanned` int(11) NOT NULL DEFAULT 0,
  `total_success` int(11) NOT NULL DEFAULT 0,
  `total_failed` int(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_date_po` (`session_date`,`po_number`),
  KEY `idx_date` (`session_date`),
  KEY `idx_po` (`po_number`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================
-- scan_session_entries
-- ============================================
CREATE TABLE IF NOT EXISTS `scan_session_entries` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `session_id` int(11) NOT NULL,
  `barcode` varchar(200) NOT NULL,
  `carton_seq` int(11) DEFAULT NULL,
  `action` varchar(10) NOT NULL,
  `success` tinyint(1) NOT NULL DEFAULT 0,
  `error_message` varchar(500) DEFAULT NULL,
  `scanned_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_session` (`session_id`),
  CONSTRAINT `fk_sse_session` FOREIGN KEY (`session_id`) REFERENCES `scan_sessions` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================
-- truck_shipments
-- ============================================
CREATE TABLE IF NOT EXISTS `truck_shipments` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `shipment_date` date NOT NULL COMMENT 'Date of shipment',
  `shipment_week` varchar(10) DEFAULT NULL COMMENT 'Week number (e.g., Wk16)',
  `truck_reg` varchar(50) NOT NULL COMMENT 'Truck registration number',
  `driver_name` varchar(100) DEFAULT NULL COMMENT 'Driver name',
  `remarks` text DEFAULT NULL COMMENT 'Remarks (e.g., shipment incomplete)',
  `loading_status` enum('open','closed') NOT NULL DEFAULT 'open' COMMENT 'open = loading in progress, closed = finished',
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `updated_at` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_shipment_date` (`shipment_date`),
  KEY `idx_truck_reg` (`truck_reg`),
  KEY `idx_dispatch_lookup` (`shipment_date`,`truck_reg`(20),`driver_name`(50),`shipment_week`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================
-- truck_shipment_items
-- ============================================
CREATE TABLE IF NOT EXISTS `truck_shipment_items` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `truck_shipment_id` int(11) NOT NULL COMMENT 'Foreign key to truck_shipments',
  `shipment_id` int(11) NOT NULL COMMENT 'Foreign key to shipments (PO)',
  `cartons_shipped` int(11) NOT NULL DEFAULT 0 COMMENT 'Number of cartons shipped',
  `units_shipped` int(11) NOT NULL DEFAULT 0 COMMENT 'Number of units shipped',
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `truck_shipment_id` (`truck_shipment_id`),
  KEY `shipment_id` (`shipment_id`),
  CONSTRAINT `truck_shipment_items_ibfk_1` FOREIGN KEY (`truck_shipment_id`) REFERENCES `truck_shipments` (`id`) ON DELETE CASCADE,
  CONSTRAINT `truck_shipment_items_ibfk_2` FOREIGN KEY (`shipment_id`) REFERENCES `shipments` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================
-- legacy_warehouse_goods
-- ============================================
CREATE TABLE IF NOT EXISTS `legacy_warehouse_goods` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `internal_po` varchar(50) NOT NULL COMMENT 'FTM PO e.g. FTM-15730',
  `customer_order_number` varchar(50) DEFAULT NULL COMMENT 'Customer order number',
  `customer` varchar(50) DEFAULT 'MRP',
  `customer_other` varchar(100) DEFAULT NULL COMMENT 'Custom customer name when customer = Other',
  `style` varchar(200) DEFAULT NULL,
  `color` varchar(100) DEFAULT NULL,
  `order_qty` int(11) DEFAULT NULL,
  `quantity_inside` int(11) DEFAULT NULL COMMENT 'Units currently in warehouse',
  `cartons_label` varchar(50) DEFAULT NULL COMMENT 'e.g. 70 CTNS',
  `cartons_count` int(11) DEFAULT NULL,
  `status` varchar(50) NOT NULL DEFAULT 'in_warehouse',
  `remarks` text DEFAULT NULL,
  `new_developments` text DEFAULT NULL,
  `shipped_qty` int(11) DEFAULT 0,
  `shipment_week` varchar(10) DEFAULT NULL COMMENT 'Outbound week e.g. Wk16',
  `shipped_at` datetime DEFAULT NULL COMMENT 'When marked shipped',
  `truck_shipment_id` int(11) DEFAULT NULL COMMENT 'Outbound truck shipment record',
  `source_year` smallint(6) DEFAULT 2025 COMMENT 'Order year e.g. 2025',
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `updated_at` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_status` (`status`),
  KEY `idx_internal_po` (`internal_po`),
  KEY `idx_customer` (`customer`),
  KEY `idx_source_year` (`source_year`),
  KEY `idx_legacy_shipment_week` (`shipment_week`),
  KEY `idx_legacy_truck_shipment_id` (`truck_shipment_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================
-- truck_shipment_legacy_items
-- ============================================
CREATE TABLE IF NOT EXISTS `truck_shipment_legacy_items` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `truck_shipment_id` int(11) NOT NULL,
  `legacy_goods_id` int(11) NOT NULL,
  `cartons_shipped` int(11) NOT NULL DEFAULT 0,
  `units_shipped` int(11) NOT NULL DEFAULT 0,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `internal_po` varchar(50) DEFAULT NULL COMMENT 'Snapshot: FTM PO at time of ship',
  `style` varchar(200) DEFAULT NULL COMMENT 'Snapshot: style at time of ship',
  `color` varchar(100) DEFAULT NULL COMMENT 'Snapshot: color at time of ship',
  `cartons_label` varchar(50) DEFAULT NULL COMMENT 'Snapshot: carton label at time of ship',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_truck_legacy_goods` (`truck_shipment_id`,`legacy_goods_id`),
  KEY `idx_legacy_goods_id` (`legacy_goods_id`),
  KEY `idx_truck_shipment_id` (`truck_shipment_id`),
  CONSTRAINT `truck_legacy_items_legacy_fk` FOREIGN KEY (`legacy_goods_id`) REFERENCES `legacy_warehouse_goods` (`id`),
  CONSTRAINT `truck_shipment_legacy_items_truck_fk` FOREIGN KEY (`truck_shipment_id`) REFERENCES `truck_shipments` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================
-- delivery_schedules
-- ============================================
CREATE TABLE IF NOT EXISTS `delivery_schedules` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `week_label` varchar(50) NOT NULL,
  `file_name` varchar(255) NOT NULL,
  `order_count` int(11) NOT NULL DEFAULT 0,
  `is_active` tinyint(1) NOT NULL DEFAULT 0,
  `imported_at` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_delivery_schedules_week_label` (`week_label`),
  KEY `idx_is_active` (`is_active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================
-- delivery_schedule_orders
-- ============================================
CREATE TABLE IF NOT EXISTS `delivery_schedule_orders` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `schedule_id` int(11) NOT NULL,
  `order_no` varchar(50) NOT NULL,
  `indent_no` varchar(50) NOT NULL,
  `description` varchar(255) DEFAULT NULL,
  `colour` varchar(255) DEFAULT NULL,
  `order_qty` varchar(50) DEFAULT NULL,
  `sewing_line` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_schedule_order` (`schedule_id`,`order_no`),
  KEY `idx_schedule_orders_order_no` (`order_no`),
  CONSTRAINT `delivery_schedule_orders_ibfk_1` FOREIGN KEY (`schedule_id`) REFERENCES `delivery_schedules` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================
-- user_audit_log
-- ============================================
CREATE TABLE IF NOT EXISTS `user_audit_log` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `action_by_user_id` int(11) NOT NULL COMMENT 'User who performed the action',
  `action_by_username` varchar(50) NOT NULL COMMENT 'Username snapshot',
  `action_type` enum('create','update','delete','activate','deactivate','role_change','password_reset') NOT NULL,
  `target_user_id` int(11) DEFAULT NULL COMMENT 'User affected by action',
  `target_username` varchar(50) DEFAULT NULL COMMENT 'Target username snapshot',
  `old_value` text DEFAULT NULL COMMENT 'JSON of old values',
  `new_value` text DEFAULT NULL COMMENT 'JSON of new values',
  `description` text DEFAULT NULL COMMENT 'Human-readable description',
  `ip_address` varchar(45) DEFAULT NULL COMMENT 'IP address of action',
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_action_by_user_id` (`action_by_user_id`),
  KEY `idx_target_user_id` (`target_user_id`),
  KEY `idx_action_type` (`action_type`),
  KEY `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================
-- schema_migrations (migration tracker)
-- ============================================
CREATE TABLE IF NOT EXISTS `schema_migrations` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `migration` varchar(255) NOT NULL,
  `batch` int(11) NOT NULL DEFAULT 1,
  `applied_at` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_schema_migrations_migration` (`migration`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
